/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SignupRouteImport } from './routes/signup'
import { Route as LoginRouteImport } from './routes/login'
import { Route as InviteRouteImport } from './routes/invite'
import { Route as AuthenticatedRouteImport } from './routes/_authenticated'
import { Route as SplatRouteImport } from './routes/$'
import { Route as AuthenticatedIndexRouteImport } from './routes/_authenticated/index'
import { Route as AuthenticatedOnboardingRouteImport } from './routes/_authenticated/onboarding'
import { Route as AuthenticatedMeRouteImport } from './routes/_authenticated/me'
import { Route as AuthenticatedActivityRouteImport } from './routes/_authenticated/activity'
import { Route as AuthenticatedTabsIndexRouteImport } from './routes/_authenticated/tabs/index'
import { Route as AuthenticatedFriendsIndexRouteImport } from './routes/_authenticated/friends/index'
import { Route as AuthenticatedTabsNewRouteImport } from './routes/_authenticated/tabs/new'
import { Route as AuthenticatedFriendsAddFriendRouteImport } from './routes/_authenticated/friends/addFriend'
import { Route as AuthenticatedFriendsAddByQrRouteImport } from './routes/_authenticated/friends/add-by-qr'
import { Route as AuthenticatedExpenseNewRouteImport } from './routes/_authenticated/expense/new'
import { Route as AuthenticatedTabsTabIdIndexRouteImport } from './routes/_authenticated/tabs/$tabId/index'
import { Route as AuthenticatedTabsTabIdMembersRouteImport } from './routes/_authenticated/tabs/$tabId/members'
import { Route as AuthenticatedTabsTabIdManageRouteImport } from './routes/_authenticated/tabs/$tabId/manage'
import { Route as AuthenticatedExpenseRecurringRuleIdRouteImport } from './routes/_authenticated/expense/recurring/$ruleId'
import { Route as AuthenticatedTabsTabIdSettlementsSettlementIdRouteImport } from './routes/_authenticated/tabs/$tabId/settlements/$settlementId'
import { Route as AuthenticatedTabsTabIdExpensesExpenseIdRouteImport } from './routes/_authenticated/tabs/$tabId/expenses/$expenseId'

const SignupRoute = SignupRouteImport.update({
  id: '/signup',
  path: '/signup',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const InviteRoute = InviteRouteImport.update({
  id: '/invite',
  path: '/invite',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRoute = AuthenticatedRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const SplatRoute = SplatRouteImport.update({
  id: '/$',
  path: '/$',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedIndexRoute = AuthenticatedIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedOnboardingRoute = AuthenticatedOnboardingRouteImport.update({
  id: '/onboarding',
  path: '/onboarding',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedMeRoute = AuthenticatedMeRouteImport.update({
  id: '/me',
  path: '/me',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedActivityRoute = AuthenticatedActivityRouteImport.update({
  id: '/activity',
  path: '/activity',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedTabsIndexRoute = AuthenticatedTabsIndexRouteImport.update({
  id: '/tabs/',
  path: '/tabs/',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedFriendsIndexRoute =
  AuthenticatedFriendsIndexRouteImport.update({
    id: '/friends/',
    path: '/friends/',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedTabsNewRoute = AuthenticatedTabsNewRouteImport.update({
  id: '/tabs/new',
  path: '/tabs/new',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedFriendsAddFriendRoute =
  AuthenticatedFriendsAddFriendRouteImport.update({
    id: '/friends/addFriend',
    path: '/friends/addFriend',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedFriendsAddByQrRoute =
  AuthenticatedFriendsAddByQrRouteImport.update({
    id: '/friends/add-by-qr',
    path: '/friends/add-by-qr',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedExpenseNewRoute = AuthenticatedExpenseNewRouteImport.update({
  id: '/expense/new',
  path: '/expense/new',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedTabsTabIdIndexRoute =
  AuthenticatedTabsTabIdIndexRouteImport.update({
    id: '/tabs/$tabId/',
    path: '/tabs/$tabId/',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedTabsTabIdMembersRoute =
  AuthenticatedTabsTabIdMembersRouteImport.update({
    id: '/tabs/$tabId/members',
    path: '/tabs/$tabId/members',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedTabsTabIdManageRoute =
  AuthenticatedTabsTabIdManageRouteImport.update({
    id: '/tabs/$tabId/manage',
    path: '/tabs/$tabId/manage',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedExpenseRecurringRuleIdRoute =
  AuthenticatedExpenseRecurringRuleIdRouteImport.update({
    id: '/expense/recurring/$ruleId',
    path: '/expense/recurring/$ruleId',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedTabsTabIdSettlementsSettlementIdRoute =
  AuthenticatedTabsTabIdSettlementsSettlementIdRouteImport.update({
    id: '/tabs/$tabId/settlements/$settlementId',
    path: '/tabs/$tabId/settlements/$settlementId',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedTabsTabIdExpensesExpenseIdRoute =
  AuthenticatedTabsTabIdExpensesExpenseIdRouteImport.update({
    id: '/tabs/$tabId/expenses/$expenseId',
    path: '/tabs/$tabId/expenses/$expenseId',
    getParentRoute: () => AuthenticatedRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/$': typeof SplatRoute
  '/': typeof AuthenticatedIndexRoute
  '/invite': typeof InviteRoute
  '/login': typeof LoginRoute
  '/signup': typeof SignupRoute
  '/activity': typeof AuthenticatedActivityRoute
  '/me': typeof AuthenticatedMeRoute
  '/onboarding': typeof AuthenticatedOnboardingRoute
  '/expense/new': typeof AuthenticatedExpenseNewRoute
  '/friends/add-by-qr': typeof AuthenticatedFriendsAddByQrRoute
  '/friends/addFriend': typeof AuthenticatedFriendsAddFriendRoute
  '/tabs/new': typeof AuthenticatedTabsNewRoute
  '/friends/': typeof AuthenticatedFriendsIndexRoute
  '/tabs/': typeof AuthenticatedTabsIndexRoute
  '/expense/recurring/$ruleId': typeof AuthenticatedExpenseRecurringRuleIdRoute
  '/tabs/$tabId/manage': typeof AuthenticatedTabsTabIdManageRoute
  '/tabs/$tabId/members': typeof AuthenticatedTabsTabIdMembersRoute
  '/tabs/$tabId/': typeof AuthenticatedTabsTabIdIndexRoute
  '/tabs/$tabId/expenses/$expenseId': typeof AuthenticatedTabsTabIdExpensesExpenseIdRoute
  '/tabs/$tabId/settlements/$settlementId': typeof AuthenticatedTabsTabIdSettlementsSettlementIdRoute
}
export interface FileRoutesByTo {
  '/$': typeof SplatRoute
  '/invite': typeof InviteRoute
  '/login': typeof LoginRoute
  '/signup': typeof SignupRoute
  '/activity': typeof AuthenticatedActivityRoute
  '/me': typeof AuthenticatedMeRoute
  '/onboarding': typeof AuthenticatedOnboardingRoute
  '/': typeof AuthenticatedIndexRoute
  '/expense/new': typeof AuthenticatedExpenseNewRoute
  '/friends/add-by-qr': typeof AuthenticatedFriendsAddByQrRoute
  '/friends/addFriend': typeof AuthenticatedFriendsAddFriendRoute
  '/tabs/new': typeof AuthenticatedTabsNewRoute
  '/friends': typeof AuthenticatedFriendsIndexRoute
  '/tabs': typeof AuthenticatedTabsIndexRoute
  '/expense/recurring/$ruleId': typeof AuthenticatedExpenseRecurringRuleIdRoute
  '/tabs/$tabId/manage': typeof AuthenticatedTabsTabIdManageRoute
  '/tabs/$tabId/members': typeof AuthenticatedTabsTabIdMembersRoute
  '/tabs/$tabId': typeof AuthenticatedTabsTabIdIndexRoute
  '/tabs/$tabId/expenses/$expenseId': typeof AuthenticatedTabsTabIdExpensesExpenseIdRoute
  '/tabs/$tabId/settlements/$settlementId': typeof AuthenticatedTabsTabIdSettlementsSettlementIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/$': typeof SplatRoute
  '/_authenticated': typeof AuthenticatedRouteWithChildren
  '/invite': typeof InviteRoute
  '/login': typeof LoginRoute
  '/signup': typeof SignupRoute
  '/_authenticated/activity': typeof AuthenticatedActivityRoute
  '/_authenticated/me': typeof AuthenticatedMeRoute
  '/_authenticated/onboarding': typeof AuthenticatedOnboardingRoute
  '/_authenticated/': typeof AuthenticatedIndexRoute
  '/_authenticated/expense/new': typeof AuthenticatedExpenseNewRoute
  '/_authenticated/friends/add-by-qr': typeof AuthenticatedFriendsAddByQrRoute
  '/_authenticated/friends/addFriend': typeof AuthenticatedFriendsAddFriendRoute
  '/_authenticated/tabs/new': typeof AuthenticatedTabsNewRoute
  '/_authenticated/friends/': typeof AuthenticatedFriendsIndexRoute
  '/_authenticated/tabs/': typeof AuthenticatedTabsIndexRoute
  '/_authenticated/expense/recurring/$ruleId': typeof AuthenticatedExpenseRecurringRuleIdRoute
  '/_authenticated/tabs/$tabId/manage': typeof AuthenticatedTabsTabIdManageRoute
  '/_authenticated/tabs/$tabId/members': typeof AuthenticatedTabsTabIdMembersRoute
  '/_authenticated/tabs/$tabId/': typeof AuthenticatedTabsTabIdIndexRoute
  '/_authenticated/tabs/$tabId/expenses/$expenseId': typeof AuthenticatedTabsTabIdExpensesExpenseIdRoute
  '/_authenticated/tabs/$tabId/settlements/$settlementId': typeof AuthenticatedTabsTabIdSettlementsSettlementIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/$'
    | '/'
    | '/invite'
    | '/login'
    | '/signup'
    | '/activity'
    | '/me'
    | '/onboarding'
    | '/expense/new'
    | '/friends/add-by-qr'
    | '/friends/addFriend'
    | '/tabs/new'
    | '/friends/'
    | '/tabs/'
    | '/expense/recurring/$ruleId'
    | '/tabs/$tabId/manage'
    | '/tabs/$tabId/members'
    | '/tabs/$tabId/'
    | '/tabs/$tabId/expenses/$expenseId'
    | '/tabs/$tabId/settlements/$settlementId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/$'
    | '/invite'
    | '/login'
    | '/signup'
    | '/activity'
    | '/me'
    | '/onboarding'
    | '/'
    | '/expense/new'
    | '/friends/add-by-qr'
    | '/friends/addFriend'
    | '/tabs/new'
    | '/friends'
    | '/tabs'
    | '/expense/recurring/$ruleId'
    | '/tabs/$tabId/manage'
    | '/tabs/$tabId/members'
    | '/tabs/$tabId'
    | '/tabs/$tabId/expenses/$expenseId'
    | '/tabs/$tabId/settlements/$settlementId'
  id:
    | '__root__'
    | '/$'
    | '/_authenticated'
    | '/invite'
    | '/login'
    | '/signup'
    | '/_authenticated/activity'
    | '/_authenticated/me'
    | '/_authenticated/onboarding'
    | '/_authenticated/'
    | '/_authenticated/expense/new'
    | '/_authenticated/friends/add-by-qr'
    | '/_authenticated/friends/addFriend'
    | '/_authenticated/tabs/new'
    | '/_authenticated/friends/'
    | '/_authenticated/tabs/'
    | '/_authenticated/expense/recurring/$ruleId'
    | '/_authenticated/tabs/$tabId/manage'
    | '/_authenticated/tabs/$tabId/members'
    | '/_authenticated/tabs/$tabId/'
    | '/_authenticated/tabs/$tabId/expenses/$expenseId'
    | '/_authenticated/tabs/$tabId/settlements/$settlementId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  SplatRoute: typeof SplatRoute
  AuthenticatedRoute: typeof AuthenticatedRouteWithChildren
  InviteRoute: typeof InviteRoute
  LoginRoute: typeof LoginRoute
  SignupRoute: typeof SignupRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/signup': {
      id: '/signup'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof SignupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/invite': {
      id: '/invite'
      path: '/invite'
      fullPath: '/invite'
      preLoaderRoute: typeof InviteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/$': {
      id: '/$'
      path: '/$'
      fullPath: '/$'
      preLoaderRoute: typeof SplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/': {
      id: '/_authenticated/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedIndexRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/onboarding': {
      id: '/_authenticated/onboarding'
      path: '/onboarding'
      fullPath: '/onboarding'
      preLoaderRoute: typeof AuthenticatedOnboardingRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/me': {
      id: '/_authenticated/me'
      path: '/me'
      fullPath: '/me'
      preLoaderRoute: typeof AuthenticatedMeRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/activity': {
      id: '/_authenticated/activity'
      path: '/activity'
      fullPath: '/activity'
      preLoaderRoute: typeof AuthenticatedActivityRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/tabs/': {
      id: '/_authenticated/tabs/'
      path: '/tabs'
      fullPath: '/tabs/'
      preLoaderRoute: typeof AuthenticatedTabsIndexRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/friends/': {
      id: '/_authenticated/friends/'
      path: '/friends'
      fullPath: '/friends/'
      preLoaderRoute: typeof AuthenticatedFriendsIndexRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/tabs/new': {
      id: '/_authenticated/tabs/new'
      path: '/tabs/new'
      fullPath: '/tabs/new'
      preLoaderRoute: typeof AuthenticatedTabsNewRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/friends/addFriend': {
      id: '/_authenticated/friends/addFriend'
      path: '/friends/addFriend'
      fullPath: '/friends/addFriend'
      preLoaderRoute: typeof AuthenticatedFriendsAddFriendRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/friends/add-by-qr': {
      id: '/_authenticated/friends/add-by-qr'
      path: '/friends/add-by-qr'
      fullPath: '/friends/add-by-qr'
      preLoaderRoute: typeof AuthenticatedFriendsAddByQrRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/expense/new': {
      id: '/_authenticated/expense/new'
      path: '/expense/new'
      fullPath: '/expense/new'
      preLoaderRoute: typeof AuthenticatedExpenseNewRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/tabs/$tabId/': {
      id: '/_authenticated/tabs/$tabId/'
      path: '/tabs/$tabId'
      fullPath: '/tabs/$tabId/'
      preLoaderRoute: typeof AuthenticatedTabsTabIdIndexRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/tabs/$tabId/members': {
      id: '/_authenticated/tabs/$tabId/members'
      path: '/tabs/$tabId/members'
      fullPath: '/tabs/$tabId/members'
      preLoaderRoute: typeof AuthenticatedTabsTabIdMembersRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/tabs/$tabId/manage': {
      id: '/_authenticated/tabs/$tabId/manage'
      path: '/tabs/$tabId/manage'
      fullPath: '/tabs/$tabId/manage'
      preLoaderRoute: typeof AuthenticatedTabsTabIdManageRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/expense/recurring/$ruleId': {
      id: '/_authenticated/expense/recurring/$ruleId'
      path: '/expense/recurring/$ruleId'
      fullPath: '/expense/recurring/$ruleId'
      preLoaderRoute: typeof AuthenticatedExpenseRecurringRuleIdRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/tabs/$tabId/settlements/$settlementId': {
      id: '/_authenticated/tabs/$tabId/settlements/$settlementId'
      path: '/tabs/$tabId/settlements/$settlementId'
      fullPath: '/tabs/$tabId/settlements/$settlementId'
      preLoaderRoute: typeof AuthenticatedTabsTabIdSettlementsSettlementIdRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/tabs/$tabId/expenses/$expenseId': {
      id: '/_authenticated/tabs/$tabId/expenses/$expenseId'
      path: '/tabs/$tabId/expenses/$expenseId'
      fullPath: '/tabs/$tabId/expenses/$expenseId'
      preLoaderRoute: typeof AuthenticatedTabsTabIdExpensesExpenseIdRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
  }
}

interface AuthenticatedRouteChildren {
  AuthenticatedActivityRoute: typeof AuthenticatedActivityRoute
  AuthenticatedMeRoute: typeof AuthenticatedMeRoute
  AuthenticatedOnboardingRoute: typeof AuthenticatedOnboardingRoute
  AuthenticatedIndexRoute: typeof AuthenticatedIndexRoute
  AuthenticatedExpenseNewRoute: typeof AuthenticatedExpenseNewRoute
  AuthenticatedFriendsAddByQrRoute: typeof AuthenticatedFriendsAddByQrRoute
  AuthenticatedFriendsAddFriendRoute: typeof AuthenticatedFriendsAddFriendRoute
  AuthenticatedTabsNewRoute: typeof AuthenticatedTabsNewRoute
  AuthenticatedFriendsIndexRoute: typeof AuthenticatedFriendsIndexRoute
  AuthenticatedTabsIndexRoute: typeof AuthenticatedTabsIndexRoute
  AuthenticatedExpenseRecurringRuleIdRoute: typeof AuthenticatedExpenseRecurringRuleIdRoute
  AuthenticatedTabsTabIdManageRoute: typeof AuthenticatedTabsTabIdManageRoute
  AuthenticatedTabsTabIdMembersRoute: typeof AuthenticatedTabsTabIdMembersRoute
  AuthenticatedTabsTabIdIndexRoute: typeof AuthenticatedTabsTabIdIndexRoute
  AuthenticatedTabsTabIdExpensesExpenseIdRoute: typeof AuthenticatedTabsTabIdExpensesExpenseIdRoute
  AuthenticatedTabsTabIdSettlementsSettlementIdRoute: typeof AuthenticatedTabsTabIdSettlementsSettlementIdRoute
}

const AuthenticatedRouteChildren: AuthenticatedRouteChildren = {
  AuthenticatedActivityRoute: AuthenticatedActivityRoute,
  AuthenticatedMeRoute: AuthenticatedMeRoute,
  AuthenticatedOnboardingRoute: AuthenticatedOnboardingRoute,
  AuthenticatedIndexRoute: AuthenticatedIndexRoute,
  AuthenticatedExpenseNewRoute: AuthenticatedExpenseNewRoute,
  AuthenticatedFriendsAddByQrRoute: AuthenticatedFriendsAddByQrRoute,
  AuthenticatedFriendsAddFriendRoute: AuthenticatedFriendsAddFriendRoute,
  AuthenticatedTabsNewRoute: AuthenticatedTabsNewRoute,
  AuthenticatedFriendsIndexRoute: AuthenticatedFriendsIndexRoute,
  AuthenticatedTabsIndexRoute: AuthenticatedTabsIndexRoute,
  AuthenticatedExpenseRecurringRuleIdRoute:
    AuthenticatedExpenseRecurringRuleIdRoute,
  AuthenticatedTabsTabIdManageRoute: AuthenticatedTabsTabIdManageRoute,
  AuthenticatedTabsTabIdMembersRoute: AuthenticatedTabsTabIdMembersRoute,
  AuthenticatedTabsTabIdIndexRoute: AuthenticatedTabsTabIdIndexRoute,
  AuthenticatedTabsTabIdExpensesExpenseIdRoute:
    AuthenticatedTabsTabIdExpensesExpenseIdRoute,
  AuthenticatedTabsTabIdSettlementsSettlementIdRoute:
    AuthenticatedTabsTabIdSettlementsSettlementIdRoute,
}

const AuthenticatedRouteWithChildren = AuthenticatedRoute._addFileChildren(
  AuthenticatedRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  SplatRoute: SplatRoute,
  AuthenticatedRoute: AuthenticatedRouteWithChildren,
  InviteRoute: InviteRoute,
  LoginRoute: LoginRoute,
  SignupRoute: SignupRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
