import { vi } from "vitest";

// Mock the data layer by default
vi.mock("data", () => ({
  expense: {
    getForTab: vi.fn(),
    getById: vi.fn(),
    create: vi.fn(),
    update: vi.fn(),
    delete: vi.fn(),
    restore: vi.fn(),
    createBulk: vi.fn(),
    addOrUpdateReaction: vi.fn(),
    removeReaction: vi.fn(),
    getAuditLog: vi.fn(),
  },
  tab: {
    isMember: vi.fn(),
    getWithMembers: vi.fn(),
    getMembers: vi.fn(),
    getCurrency: vi.fn().mockResolvedValue("USD"),
    getTabInfoForNotifications: vi.fn(),
    create: vi.fn(),
    update: vi.fn(),
    addMember: vi.fn(),
    removeMember: vi.fn(),
    getTabsForUser: vi.fn(),
    getBalancesForTab: vi.fn(),
    listGroupTabsSharedBetweenUsers: vi.fn(),
    createDirect: vi.fn(),
  },
  settlement: {
    getForTab: vi.fn(),
    getById: vi.fn(),
    getAuditLog: vi.fn(),
    record: vi.fn(),
    update: vi.fn(),
    delete: vi.fn(),
  },
  user: {
    getById: vi.fn(),
    getByIds: vi.fn(),
    getDefaultCurrency: vi.fn(),
    getByUsername: vi.fn(),
    getByEmail: vi.fn(),
    getUsername: vi.fn(),
    getByUsernameForId: vi.fn(),
    updateProfile: vi.fn(),
    updateUsername: vi.fn(),
  },
  friend: {
    getDirectTabBetween: vi.fn(),
    getPendingRequests: vi.fn(),
    checkExistingRequest: vi.fn(),
    checkReverseRequest: vi.fn(),
    createRequest: vi.fn(),
    getRequestByIdAndToUser: vi.fn(),
    updateRequestStatus: vi.fn(),
    updateRequestStatusForToUser: vi.fn(),
    getPendingFriendByToken: vi.fn(),
    getPendingFriendByUser: vi.fn(),
    deletePendingFriend: vi.fn(),
    createPendingFriend: vi.fn(),
    getDirectTabIdsForUser: vi.fn(),
    getOtherMemberOfDirectTab: vi.fn(),
    isUserInDirectTab: vi.fn(),
    searchUsers: vi.fn(),
  },
  tabInvite: {
    getPendingByToken: vi.fn(),
    getPendingInviteByToken: vi.fn(),
    getTabById: vi.fn(),
    getUserById: vi.fn(),
    isMember: vi.fn(),
    getMembers: vi.fn(),
    deletePendingInvite: vi.fn(),
    getExistingPendingByTabAndCreator: vi.fn(),
    deletePendingInvitesByTabAndCreator: vi.fn(),
    generateToken: vi.fn(),
    createPendingInvite: vi.fn(),
    getPendingRequests: vi.fn(),
    getRequestByIdAndToUser: vi.fn(),
    updateRequestStatus: vi.fn(),
    checkExistingRequest: vi.fn(),
    createRequest: vi.fn(),
  },
  preference: {
    getByUserId: vi.fn(),
    upsert: vi.fn(),
    delete: vi.fn(),
  },
  fxRate: {
    getSnapshot: vi.fn(),
    upsertSnapshot: vi.fn(),
  },
}));

// Mock notificationService
vi.mock("../notification.js", () => ({
  notificationService: {
    publishExpenseAddedToUser: vi.fn(),
    publishExpenseUpdatedToUser: vi.fn(),
    publishExpenseDeletedToUser: vi.fn(),
    publishExpenseRestoredToUser: vi.fn(),
    publishExpensesBulkImportedToUser: vi.fn(),
    publishExpenseReactionToUser: vi.fn(),
    publishFriendRequest: vi.fn(),
    publishFriendRequestAccepted: vi.fn(),
    publishPoke: vi.fn(),
    publishTabInvite: vi.fn(),
    publishTabInviteAccepted: vi.fn(),
  },
}));
